grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2
    n_jobs: -1

model_selection:
  model_0:
    module: sklearn.ensemble
    class: RandomForestClassifier
    params:
      n_estimators: 50
      max_depth: 5
      max_features: sqrt
    search_param_grid:
      n_estimators: [50, 100]
      max_depth: [5, 10]
      max_features: ["sqrt", "log2"]

  model_1:
    module: sklearn.ensemble
    class: GradientBoostingClassifier
    params:
      n_estimators: 50
      learning_rate: 0.1
      max_depth: 3
    search_param_grid:
      n_estimators: [50, 100]
      learning_rate: [0.05, 0.1]
      max_depth: [3, 5]

  model_2:
    module: sklearn.linear_model
    class: LogisticRegression
    params:
      solver: lbfgs
      max_iter: 200
    search_param_grid:
      C: [0.1, 1.0]
      penalty: ["l2"]
