GradientBoostingClassifier:
  best_params:
    learning_rate: 0.05
    max_depth: 3
    n_estimators: 100
  module_name: sklearn.ensemble
  test_metrics:
    accuracy: 0.9
    f1: 0.9
    precision: 0.9
    recall: 0.9
  train_metrics:
    accuracy: 0.99375
    f1: 0.9937507326794577
    precision: 0.9938291139240507
    recall: 0.99375
  train_score: 0.99375
LogisticRegression:
  best_params:
    C: 1.0
    penalty: l2
  module_name: sklearn.linear_model
  test_metrics:
    accuracy: 0.925
    f1: 0.9236668861092824
    precision: 0.9336538461538462
    recall: 0.925
  train_metrics:
    accuracy: 0.93125
    f1: 0.9312580569553498
    precision: 0.9319210032817626
    recall: 0.93125
  train_score: 0.93125
RandomForestClassifier:
  best_params:
    max_depth: 10
    max_features: sqrt
    n_estimators: 100
  module_name: sklearn.ensemble
  test_metrics:
    accuracy: 0.9
    f1: 0.8989583333333332
    precision: 0.9026666666666667
    recall: 0.9
  train_metrics:
    accuracy: 1.0
    f1: 1.0
    precision: 1.0
    recall: 1.0
  train_score: 1.0
