grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      max_depth: 3
      min_child_weight: 1
      learning_rate: 0.1
      n_estimators: 100
    search_param_grid:
      max_depth:
        - 3
        - 5
        - 7
        - 9
      min_child_weight:
        - 1
        - 3
        - 5
      learning_rate:
        - 0.01
        - 0.05
        - 0.1
        - 0.2
      n_estimators:
        - 50
        - 100
        - 200
        - 300

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 100
      min_samples_split: 2
      min_samples_leaf: 1
    search_param_grid:
      max_depth:
        - 10
        - 12
        - null
        - 15
        - 20
      max_features:
        - sqrt
        - log2
        - null
      n_estimators:
        - 50
        - 100
        - 200
        - 300
      min_samples_split:
        - 2
        - 5
        - 10
      min_samples_leaf:
        - 1
        - 2
        - 4

  module_2:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: auto
      weights: uniform
      n_neighbors: 5
      p: 2
    search_param_grid:
      algorithm:
        - auto
        - ball_tree
        - kd_tree
        - brute
      weights:
        - uniform
        - distance
      n_neighbors:
        - 3
        - 4
        - 5
        - 7
        - 9
        - 11
      p:
        - 1
        - 2

  module_3:
    class: CatBoostClassifier
    module: catboost
    params:
      depth: 6
      learning_rate: 0.1
      iterations: 200
      l2_leaf_reg: 3
      verbose: 0
    search_param_grid:
      depth:
        - 4
        - 6
        - 8
        - 10
      learning_rate:
        - 0.01
        - 0.05
        - 0.1
        - 0.2
      iterations:
        - 100
        - 200
        - 300
      l2_leaf_reg:
        - 1
        - 3
        - 5
        - 7

  module_4:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      max_depth: null
      criterion: gini
      min_samples_split: 2
      min_samples_leaf: 1
      max_features: null
    search_param_grid:
      max_depth:
        - null
        - 5
        - 10
        - 15
        - 20
      criterion:
        - gini
        - entropy
        - log_loss
      min_samples_split:
        - 2
        - 5
        - 10
      min_samples_leaf:
        - 1
        - 2
        - 4
      max_features:
        - null
        - sqrt
        - log2
