grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 1
    n_jobs: -1

model_selection:
  model_0:
    module: sklearn.ensemble
    class: RandomForestClassifier
    params:
      n_estimators: 10
      max_depth: 3
      max_features: sqrt
    search_param_grid:
      n_estimators: [10, 20]
      max_depth: [3, 5]
      max_features: ["sqrt", "log2"]

  model_1:
    module: sklearn.neighbors
    class: KNeighborsClassifier
    params:
      n_neighbors: 3
      weights: uniform
      algorithm: auto
    search_param_grid:
      n_neighbors: [3, 5]
      weights: ["uniform", "distance"]
      algorithm: ["auto", "ball_tree"]
